namespace SpriteKind {
    export const energy = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -190
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile6`, function (sprite, location) {
    game.gameOver(false)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (characterAnimations.matchesRule(mySprite, characterAnimations.rule(Predicate.FacingRight))) {
        projectile = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .............c..........
            .............ccccccc....
            .............cddddd.....
            .............ccccc......
            .............c..........
            ........................
            `, mySprite, 0, 0)
    } else if (characterAnimations.matchesRule(mySprite, characterAnimations.rule(Predicate.FacingLeft))) {
        projectile = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........c.............
            ....ccccccc.............
            .....dddddc.............
            ......ccccc.............
            ..........c.............
            ........................
            `, mySprite, 0, 0)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile9`, function (sprite, location) {
    scene.setBackgroundImage(img`
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffcfffffffffffffffffffffffffffffcccccfffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffcfccfffffffffffffffffffffffffffffccccffffffffffffffffff
        ffffccccfffccfffffcccccccccffffffccccccccffffffcccccccccfffffcccffffcccfffffccccccccffffffcccccccccfffffcccccccccffffffcccccccccfffffcccccccccfffffcccccccccffff
        ffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffcccccffffcccfffcccccccccccffcccccccccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        ffffffccccccccffffffcccccccccffcffcccccccccffffffccccccccffffffcccccccccffffffccccccccffcfffcccccccccffcffcccccccccffffffccccccccfffcffccccccccfffcffcccccccccff
        ffffffccccccccffffffcccccccffffcffcccccccccffffffccccccccffffffcccccccccffffffccccccccffcfffcccccccccffcffcccccccccffffffccccccccfffcffccccccccfffcffcccccccccff
        fffcccccccccccfffccccccccccffffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffcccccccccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffcccccccccccfffccccccccccffffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffffcccccccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffcccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccfffffffccccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffcccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccffffffffcccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffccccccccffcfffccccffcccfccfffccccccccffcffffccccccccfcfffcccccccccffcffcccccccccffcffcffffcccccccfffccccffcccffcfffccccccccffcfffccccffcccfffffcccccccccffcff
        ffffcccccccfffffffcffffccfffcffffcccccccfffffffcccccccfffffffcffccccffffffffcccccccfffffffccccccccfffffffffffcccfffffffcccccccfffffffcffffccffffffffccffcccfffff
        ffffccccccccfffffffffffcccfffffffccccccccffffffcccccccfffffffcfffccccfffffffccccccccffffffccccccccfffffffffffccccffffffccccccccfffffffffffcccfffffffccfffccfffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffcffffffcccccccccffffffcccccccccfffffcccccccccffffffccccccccffffffccccfffcffffffcccccccccffffffccccccccffffffcccccccccffffffccccccccffffffccccfffcffffffccccff
        ffccccffffccccccccccffffccccccccccffffcccccccccccffffccccccccccffffccccccfffcffffcccccccccccfffcccccccccccffffccccccccccffffcccccccccccffffcccccffffcffffccccccf
        ccccccffffffcccccccccffffffccccccccffffffcccfffccfffcfccccccccccffcffccccfffccffffffcccccccccfffffcccccccccffcfffccccccccffccffccccccccfffcffccccfffccffffffcccc
        ccccccffffffcccccccffffcfffccccccccffffffcccffffffffcffcccccccccffcffcccccccccffffffcccccccccffffffccccccccffcfffcccccccccffcffccccccccfffcffcccccccccffffffcccc
        ccccccfffcffcccccccffffcffcccccccccfffcffccccfffffffccccccccccccffcffcccccccccfffcfccccccccccffcffcccccccccffccfccccccccccfccffccccccccfffcffcccccccccfffffccccc
        ccccccfffccccccccccffffccccccccccccfffccccccccffffffccccccccccccffccccccccccccffffcccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffcccccccccccfffccccccccccccffffcccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffcccccccccccffcccccccccccfffccccccccccccffcfcccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffccccffcccccfffccccccccccccffcccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        cccffffffccccccccfffcffcccccccccffffffcccccccccfffffccccfffcfffffffccccccccfffffcccccccccffffffccccccccfffffffccccccccffffffcccccccccffffffccccccccffcfffccccccc
        cccfffffffcfffcccffffffffcccccccfffffffccccccccfffffffffffcccfffffffcccccccfffffffcccccccfffffffffffcccffffffffcccccccfffffffffffccccfffffffccfffccfffffffccfffc
        ffffffffffcffffffffffffffffffffffffffffffcfcccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffcffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffccccfffccffffffccccccccffffffcccccccccfffffcccccccccfffffcccccccccffffffccccfffffffffffccccccccffffffcccccccccfffffcccccccccfffffcccccccccfffffcccccccccffff
        fffccccccfcccffffccccccccccfffffcccccccccccfffccccccccccfffffccccccccccfffccccccffffcffffccccccccccfffffccccccccccffffccccccccccfffffcccccccccccffcccccccccccfff
        fffcccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccffcccccccfffccffccccccccccccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccff
        ffcfffccccccccffffffcccccccccffcffcccccccccffffffccccccccffffffcccccccccffcfffccccccccffcfffccccccccffffffcccccccccffffffccccccccfffcffcccccccccffcffcccccccccff
        ffccfcccccccccffffffcccccccffffcffcccccccccffffffccccccccffffffcccccccccffcffcccccccccffcfffccccccccffffffcccccccccffffffccccccccfffcffcccccccccffcffcccccccccff
        ffccccccccccccfffccccccccccffffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccff
        ffccccccccccccfffccccccccccffffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        ffccccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffcccccccccccfffccccffccccccffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffccccccccffffffccccffccfffcffcccccccccffcfffccccccccffffffcccccccccfffffcccccccccfffffcccccccccffffffcccccccccffcfffccccccccffffffccccffccffffffcccccccccfffff
        ffffccccccccffffffffffcccccffffffccccccccffffffcccccccccfffffcccccccccffffffccccccccffffffcccccccccfffffffffcccccffffffcccccccccfffffcffccccccffffffccfffcccffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffcccfffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccffffffffffffffffffffffffff
        ffcccfffffcccccccccfffffccccccccccfffffcccccccccfffffccccccccccffffcccccffffffffffcccccccccfffffccccccccccffffccccccccccfffffcccccccccfffffcccccccccfffffcccccff
        ccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccfffccfffcccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccffffffcccccccccffcfffccccccccffffffccccccccfffcffcccccccccfffffccccfffccffffffcccccccccffffffccccccccffcfffccccccccffffffccccccccfffcffcccccccccffffffcccc
        ccccccffffffcccccccffffcfffccccccccffffffcccccccffffcffcccccccccffcffcccccccccffffffcccccccccffffffccccccccffcfffccccccccffffffccccccccfffcffcccccccccffffffcccc
        ccccccfffccccccccccffffccccccccccccfffccccccccccffffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccffffccccccccccccfffccccccccccffffccccccccccccffccccccccccccffffcccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccffffcccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        cccffffffccccffcccfccffcccccccccfffffffcccccccffffffcccccccccffffffccccccccffffffcccccccccffcffccccffcccffcffcccccccccffffffcccccccccfffffcccccccccffcfffccccccc
        cccfffffffccfffcccffcffffcccccccfffffffcccccccfffffffcccccccfffffffccccccccfffffffcccccccfffffffccffffcffffffffcccccccfffffffcffcccccffffffcccffcccfffffffcccfcc
        cccfffffffffffcccccffffffcccccccfffffffcccccccffffffffcccccccfffffffcccccccfffffffcccccccffffffffffffcccfffffffcccccccfffffffffffccccfffffffccfffccfffffffcccffc
        fffffffffffffffcfcfffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffcfccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffcffffffffffffffffffffffffffffffffffcfccfffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccffffff
        ffffccccfffccfffffcccccccccffffffccccccccffffffcccccccccfffffcccccccccffffffccccfffccfffffcccccccccffffffccccccccffffffcccccccccfffffcccccccccffffffccccccccffff
        fffccccccccccccffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccffccffccccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccff
        ffffffccccccccffffffcccccccccffcfffccccccccfffcffccccccccfffcffcccccccccffffffccccffccffcfffccccccccffffffcccccccccffcfffccccccccfffcffccccccccfffcffcccccccccff
        ffffffccccccccffffffcccccccccffcffcccccccccffccffccccccccffffffcccccccccffcffcccccccccffcfffccccccccffffffcccccccccffffffccccccccfffcffccccccccfffcffcccccccccff
        fffffcccccccccffffffcccccccffffcffcccccccccffffffccccccccfffcffcccccccccfffffcccccccccffcfffccccccccfffcffcccccccccfffffcccccccccfffcffccccccccfffccccccccccccff
        fffcccccccccccfffccccccccccffffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccff
        fffcccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        ffccccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccff
        ffccccccccccccfffccccffccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccffccccccfffcccccccccccfffccccccccccccffccccccccccccff
        ffcccccccccffffffccccffcccffcffcccccccccffcffffcccccccffffffccccccccfffcffcccccccccfffffcccccccccffffffccccffcccffcfffccccccccffffffcccccccccffcffcccccccccfffff
        ffffcccccccffffffffffffcccfffffffcccccccfffffffcccccccfffffffcccccccffffffffcccccccfffffffcccccccffffffffcfffcccfffffffcccccccfffffffcfffccccfffffffccfffccfffff
        ffffcccccccccfffffffffcccccffffffccccccccffffffcccccccccfffffcccccccccffffffccccccccffffffcccccccccfffffccfccccccffffffcccccccccfffffcfffcccccffffffccfffcccffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffcffffffcccccccccffffffcccccccccfffffcccccccccffffffccfffcccffffffccccffccffffffcccccccccffffffcccccccccfffffcccccccccffffffccccccccffffffccccccccffffffccccff
        ffcccfffffcccccccccfffffccccccccccfffffcccccccccfffffcccffccccfffffcccccffccffffffcccccccccfffffcccccccccfffffccccccccccfffffcccccccccfffffcccccccccfffffcccccff
        ccccccfffccccccccccccffccccccccccccfffcccccccffccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccffffffcccccccccffcfffccccccccffffffcccfffccffffffccccccccffffffcccccccccffffffcccccccccfffffcccccccccffcfffccccccccffffffccccccccfffcffcccccccccffffffcccc
        ccccccfffcffcccccccffffcfffccccccccffffffccccfffffffcffcccccccccfffffcccccccccffffffcccccccccffccfcccccccccffcfffccccccccffffffccccccccfffcffcccccccccffffffcccc
        ccccccfffccccccccccffffccccccccccccfffccccccccffffffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        cccffffffccccccccfffcffcccccccccfffffffcccccccffffffcccccccccffcffcccccccccffffffccccccccfffcffccccfffcfffcffcccccccccffffffcccccccccfffffcccccccccffcfffccccccc
        cccfffffffcfffcccffffffffcccccccfffffffcccccccfffffffcffcccccfffffffcccccccfffffffcccccccfffffffffffffcffffffffcccccccfffffffcffcccccfffffffccfffccfffffffccfffc
        ccccffffffffffcccccffffffccccccccffffffcccccccccffffffffccccccffffffccccccccffffffcccccccccfffffffffcccccffffffcccccccccfffffcfffcccccffffffccfffcccffffffccfffc
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffcccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccfffffffffffffffffffffffffffffffff
        ffffccccffcccfffffcccccccccfffffcccccccccffffffcccccccccfffffcccffccccfffffccccccccccfffffcccccccccfffffcccccccccffffffcccccccccfffffcccccccccfffffcccccccccffff
        fffcccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        ffffffcccccccccfccffcccccccccffcffcccccccccffffffccccccccffffffcccccccccffffffccccccccffcfffccccccccffffffcccccccccffcffcccccccccfffcffccccccccfffcffcccccccccff
        ffffffcccccccccffcffcccccccffffcffcccccccccffffffcccccccfffffffcccccccccffcfffcccccccccfcfffccccccccffffffcccccccccffcffcccccccccfffcffccccccccfffcffcccccccccff
        fffccccccccccccfcccccccccccffffccccccccccccfffccccccccccffffccccccccccccffcccccccccccccfccccccccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccff
        fffccccccccccccffccccccccccfffffcccccccccccfffccccccccccffffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffccccccccccccffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffcccccccccccfffccccccccccccfffcccccccccccffffccccccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        fffccccccccccffffccccffcccffcffcccccccccffcffffcccccccffffffccccffcccffcffcccccccccfffffcccccccccffffffcccccccccfccfffccccccccffcfffccccffccffffffcccccccccffcff
        fffccccccccffffffccccffccfffcffcccccccccffcffcccccccccffffffccccfffcffffffcccccccccfffffcccccccccffffffcccccccccffcfffccccccccffffffcccfffccffffffcccccccccfffff
        ffffccccccccfffffffffffcccfffffffccccccccffffffccccccccffffffcffffccccffffffccccccccffffffccccccccffffffffffcccccffffffccccccccfffffffffffcccffffffcccfffcccffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffcccfffffcccccccccffffffcccccccccfffffcccccccccfffffcccccccccffffffccccffccffffffcccccccccfffffcccccccccffffffcccccccccfffffcccccccccffffffcccfffffffffffccccff
        ccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffcccccccffccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffcccccccfffccfffccccccc
        ccccccffffffcccccccccffcfffccccccccfffcffccccccccffffffcccccccccfffffcccccffccffffffcccccccccfffffcccccccccffcfffccccccccffffffccccccccfffcffccccfffccffffffcccc
        ccccccffffffcccccccffffffffccccccccffffffcccccccfffffffcccccccccfffffcccccccccffffffcccccccccffffffccccccccffcfffccccccccffffffccccccccfffcffcccccccccffffffcccc
        ccccccfffccccccccccffffccccccccccccfffccccccccccffffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccfffccccccc
        ccccccfffccccccccccffffccccccccccccfffccccccccccffffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccfffcccccccccccfffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccffccccccccccccfffccccccc
        ccccccfffccccccccccccffccccccccccccffffccccccccccfffccccccccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccccccccccffccccccccccccfffccccccc
        ccccccfffccccffccccccffccccccccccccffffccccccccccfffccccffccccccffccccccccccccfffccccccccccccffccccccccccccffccccccccccccfffccccffccccccffccccccccccccfffccccccc
        cccffffffccccffccfffcffcccccccccffcfffccccccccffffffccccfffccffcffcccccccccffffffccccccccfffcffccccccccfffcffcccccccccffffffccccffcccffcffcccccccccffcfffccccccc
        cccffffffffffffccffffffffcccccccfffffffcccccccffffffffffffcccfffffffcccccccfffffffcccccccfffffffffffcccffffffffcccccccffffffffffffcccfffffffccfffccfffffffccfffc
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffcccfffccffffffccccccccffffffccccccccffffffcccccccccfffffcccccccccffffffccccffccfffffffccccccccffffffccccccccffffffcccccccccfffffffcccccccffffffccccffccffff
        fffcccccffcccfffffcccccccccfffffccccccccccffffccccccccccfffffcccccccccfffffcccccffffcffffccccccccccfffffccccccccccffffccccccccccfffffcccccccccfffffcccccffffffff
        fffcccccccccccfffccccccccccccffccccccccccccfffcccccccffccfffccccccccccccffcccccccfffccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffcccccccfffccff
        ffffffccccccccffffffcccccccccffcffcccccccccffffffccccffccffffffcccccccccffcfffccccccccffcfffccccccccffffffcccccccccffffffccccccccffffffccccccccfffcffcccccccccff
        ffffffccccccccfffffccccccccffffcffcccccccccffffffccccffffffffffcccccccccffcffcccccccccffccccccccccccfffcffcccccccccffffffccccccccfffcffccccccccfffcffcccccccccff
        fffcccccccccccfffccccccccccffffccccccccccccfffccccccccffffffccccccccccccffccccccccccccffccccccccccccfffccccccccccccfffcccccccccccfffcccccccccccfffccccccccccccff
        `)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    tiles.loadMap(tiles.createSmallMap(tilemap`level24`))
    tiles.placeOnRandomTile(mySprite, assets.tile`myTile10`)
    for (let value of tiles.getTilesByType(assets.tile`myTile7`)) {
        monster1 = sprites.create(img`
            . . 9 9 9 . . . 
            . 9 6 6 6 9 . . 
            9 2 9 9 9 6 9 . 
            9 9 6 6 9 9 6 9 
            . 9 9 9 . . 9 . 
            . . . . . . . . 
            . . . . . . . . 
            . . . . . . . . 
            `, SpriteKind.Enemy)
        monster1.ay = 500
        monster1.vx = -30
        tiles.setTileAt(value, assets.tile`transparency8`)
        tiles.placeOnTile(monster1, value)
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    sprites.destroy(otherSprite, effects.disintegrate, 500)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    scene.cameraShake(4, 500)
    mySprite.startEffect(effects.fire, 1000)
    pause(1000)
})
let projectile: Sprite = null
let monster1: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffff
    ffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffc
    fffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffff
    fffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcffffffffffff
    fff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbffffffffffff
    ffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffff
    f33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccffffffffffffffffffff
    ff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffff
    ffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffff
    fffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcffff
    fffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcfffff
    ffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffff
    fffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcffffffffffff
    fffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffff
    cffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffff
    ffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffff
    ffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffff
    ffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fff
    ffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bff
    ffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333f
    ffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ff
    fffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbff
    ffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffff
    fffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcfffffffffff
    fffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcffffffffff
    ffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcf
    ffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffff
    fffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffff
    ffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffcffffffffffffffffcbcffffffffffffffffffffc
    fffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffff
    fffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcffffffffffff
    fff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbfffffffffffffff3fffffffffffffffffffffbbbffffffffffff
    ffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffffffb3bffffffffffffffffffffcbcffffffffffff
    f33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccfffffffffffffffffffff33333ffffffffffffccffffffffffffffffffff
    ff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffffff3b3fffffffffffffccffffffffffffffffffff
    ffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffffffbfbfffffffffffffffffffffffffffffcfffff
    fffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcffff
    fffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcfffff
    ffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffff
    fffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcfffffffffffffcfffffffffffffffffffffffffcffffffffffff
    fffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffcffffffffffcffffff
    cffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffffcffffffffffffffffffffcbcffffffffffffffff
    ffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffcffffffffffff
    ffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffff
    ffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fffffffffffffffbbbfffffffffffffffffffff3fff
    ffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bffffffffffffffcbcffffffffffffffffffffb3bff
    ffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333fffffffffffffffffffffccffffffffffff33333f
    ffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ffffffffffffffffffffffccfffffffffffff3b3ff
    fffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbfffffffcfffffffffffffffffffffffffffffbfbff
    ffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffff
    fffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcffffffffffffffffcffffffffffffffffffffffcfffffffffff
    `)
tiles.loadMap(tiles.createSmallMap(tilemap`level12`))
mySprite = sprites.create(img`
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . . 
    `, SpriteKind.Player)
tiles.placeOnRandomTile(mySprite, assets.tile`myTile10`)
profilelife.setMaxLife(10)
info.setLife(10)
profilelife.setFilledLifeImage(img`
    . f f . . . f f . 
    f f 2 f . f 2 f f 
    f 2 2 2 f 2 2 2 f 
    f 2 2 2 2 2 2 2 f 
    . f 2 2 2 2 1 f . 
    . . f 2 2 1 f . . 
    . . . f 2 f . . . 
    . . . . f . . . . 
    `)
profilelife.setEmptyLifeImage(img`
    . f f . . . f f . 
    f . . f . f . . f 
    f . . . f . . . f 
    f . . . . . . . f 
    . f . . . . . f . 
    . . f . . . f . . 
    . . . f . f . . . 
    . . . . f . . . . 
    `)
scene.cameraFollowSprite(mySprite)
mySprite.setStayInScreen(true)
mySprite.ay = 500
controller.moveSprite(mySprite, 100, 0)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . . f f f . . . . . . 
    `],
500,
characterAnimations.rule(Predicate.NotMoving, Predicate.FacingRight, Predicate.HittingWallDown)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d d 4 e e e f . . . 
    . . . f e 4 4 4 e e f f . . . . 
    . . . f 2 2 2 e d d 4 . . . . . 
    . . . f 2 2 2 e d d e . . . . . 
    . . . f 5 5 4 f e e f . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f f . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d d 4 e e e f . . . 
    . . . f e 4 4 4 e e f f . . . . 
    . . . f 2 2 2 e d d 4 . . . . . 
    . . . f 2 2 2 e d d e . . . . . 
    . . . f 5 5 4 f e e f . . . . . 
    . . . . . . f f f . . . . . . . 
    `],
500,
characterAnimations.rule(Predicate.NotMoving, Predicate.FacingLeft, Predicate.HittingWallDown)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e e e d d d f . . . 
    . . . . . f 4 d d e 4 e f . . . 
    . . . . . f e d d e 2 2 f . . . 
    . . . . f f f e e f 5 5 f f . . 
    . . . . f f f f f f f f f f . . 
    . . . . . f f . . . f f f . . . 
    `,img`
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . 4 d d e 4 4 4 e f . . . 
    . . . . e d d e 2 2 2 2 f . . . 
    . . . . f e e f 4 4 5 5 f f . . 
    . . . . f f f f f f f f f f . . 
    . . . . . f f . . . f f f . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingRight, Predicate.HittingWallDown)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d d 4 e e e f . . . 
    . . . f e 4 4 4 e e f f . . . . 
    . . . f 2 2 2 e d d 4 . . . . . 
    . . . f 2 2 2 e d d e . . . . . 
    . . . f 5 5 4 f e e f . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f f . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d e e e e e f . . . 
    . . . f e 4 e d d 4 f . . . . . 
    . . . f 2 2 e d d e f . . . . . 
    . . f f 5 5 f e e f f f . . . . 
    . . f f f f f f f f f f . . . . 
    . . . f f f . . . f f . . . . . 
    `,img`
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d d 4 e e e f . . . 
    . . . f e 4 4 4 e e f f . . . . 
    . . . f 2 2 2 e d d 4 . . . . . 
    . . . f 2 2 2 e d d e . . . . . 
    . . . f 5 5 4 f e e f . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . . . . f f f . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 d 4 e e f . . 
    . . . f d d d d 4 e e e f . . . 
    . . . f e 4 4 4 e d d 4 . . . . 
    . . . f 2 2 2 2 e d d e . . . . 
    . . f f 5 5 4 4 f e e f . . . . 
    . . f f f f f f f f f f . . . . 
    . . . f f f . . . f f . . . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingLeft, Predicate.HittingWallDown)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 e e e e f . . 
    . . . f d d d d e d d e f . . . 
    . . . f e 4 4 4 e d d e . . . . 
    . . . f 2 2 2 2 f e e f . . . . 
    . . f f 5 5 4 4 f f f . . . . . 
    . . f f f f f f f f f . . . . . 
    . . . f f f . . . f f . . . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingUp, Predicate.FacingLeft)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e e e 4 1 f d d e f . . 
    . . . f e d d e d d d d f . . . 
    . . . . e d d e 4 4 4 e f . . . 
    . . . . f e e f 2 2 2 2 f . . . 
    . . . . . f f f 4 4 5 5 f f . . 
    . . . . . f f f f f f f f f . . 
    . . . . . f f . . . f f f . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingUp, Predicate.FacingRight)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e e e 4 1 f d d e f . . 
    . . . f e d d e d d d d f . . . 
    . . . . e d d e 4 4 4 e f . . . 
    . . . . f e e f 2 2 2 2 f . . . 
    . . . . . f f f 4 4 5 5 f f . . 
    . . . . . f f f f f f f f f . . 
    . . . . . f f . . . f f f . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingDown, Predicate.FacingRight)
)
characterAnimations.loopFrames(
mySprite,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f 2 f e e e e f f . . . . 
    . . f 2 2 2 f e e e e f f . . . 
    . . f e e e e f f e e e f . . . 
    . f e 2 2 2 2 e e f f f f . . . 
    . f 2 e f f f f 2 2 2 e f . . . 
    . f f f e e e f f f f f f f . . 
    . f e e 4 4 f b e 4 4 e f f . . 
    . . f e d d f 1 4 e e e e f . . 
    . . . f d d d d e d d e f . . . 
    . . . f e 4 4 4 e d d e . . . . 
    . . . f 2 2 2 2 f e e f . . . . 
    . . f f 5 5 4 4 f f f . . . . . 
    . . f f f f f f f f f . . . . . 
    . . . f f f . . . f f . . . . . 
    `],
100,
characterAnimations.rule(Predicate.MovingDown, Predicate.FacingLeft)
)
for (let value of tiles.getTilesByType(assets.tile`myTile7`)) {
    monster1 = sprites.create(img`
        . . 9 9 9 . . . 
        . 9 6 6 6 9 . . 
        9 2 9 9 9 6 9 . 
        9 9 6 6 9 9 6 9 
        . 9 9 9 . . 9 . 
        . . . . . . . . 
        . . . . . . . . 
        . . . . . . . . 
        `, SpriteKind.Enemy)
    monster1.ay = 500
    monster1.vx = -30
    tiles.setTileAt(value, assets.tile`transparency8`)
    tiles.placeOnTile(monster1, value)
}
game.onUpdate(function () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        if (value.isHittingTile(CollisionDirection.Right)) {
            value.vx = -30
            value.image.flipX()
        } else if (value.isHittingTile(CollisionDirection.Left)) {
            value.vx = 30
            value.image.flipX()
        } else if (!(value.isHittingTile(CollisionDirection.Bottom))) {
            value.vx = -1 * value.vx
            value.image.flipX()
        }
    }
})
